"""meshtasticd config.d/ overlays: sanitize on activation, audit what is active.

2026-09-28: meshanchor-server's config.d/usb-serial.yaml (written by our own
setup wizard) carried `Webserver: Port: 443` for five months, and MeshAnchor
had no activation sanitizer and no surface that would show it. Port of
MeshForge's sanitizer + Config Doctor overlay check (#58).
"""
import os
import re
import sys
from pathlib import Path
from unittest.mock import MagicMock, patch

sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', 'src', 'launcher_tui'))
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', 'src'))

import yaml

from utils import meshtasticd_overlay as mo

# The exact file meshanchor-server carried (before 2026-09-28).
OLD_USB_SERIAL = """\
# USB Serial Configuration
# Generated by MeshAnchor Setup Wizard

Serial:
  Device: /dev/ttyUSB0

TCP:
  Port: 4403

Webserver:
  Port: 443

Logging:
  LogLevel: info
"""

SRC = Path(__file__).parent.parent / "src"


def test_forbidden_keys_match_meshforge():
    # MeshForge core.meshtasticd_templates.HAT_OVERLAY_FORBIDDEN_KEYS.
    assert mo.HAT_OVERLAY_FORBIDDEN_KEYS == {
        'Webserver', 'TCP', 'Logging', 'MQTT', 'Bluetooth', 'General'}


def test_sanitize_strips_forbidden_keeps_the_rest():
    text, stripped = mo.sanitize_hat_overlay(OLD_USB_SERIAL)
    assert stripped == ['Logging', 'TCP', 'Webserver']
    assert yaml.safe_load(text) == {'Serial': {'Device': '/dev/ttyUSB0'}}


def test_sanitize_leaves_clean_and_malformed_alone():
    clean = "Lora:\n  Module: sx1262\n"
    assert mo.sanitize_hat_overlay(clean) == (clean, [])
    bad = "Lora: [unclosed\n"
    assert mo.sanitize_hat_overlay(bad) == (bad, [])


def test_install_overlay_writes_sanitized(tmp_path):
    src = tmp_path / "usb-serial.yaml"
    src.write_text(OLD_USB_SERIAL)
    dst = tmp_path / "out.yaml"
    assert "Webserver" in mo.install_overlay(src, dst)
    assert "Webserver" not in yaml.safe_load(dst.read_text())


def test_audit_absent(tmp_path):
    assert mo.audit_overlays(tmp_path / "nope") == ('absent', [])


def test_audit_flags_the_real_file(tmp_path):
    (tmp_path / "usb-serial.yaml").write_text(OLD_USB_SERIAL)
    status, lines = mo.audit_overlays(tmp_path)
    assert status == 'port_moved'
    assert any("Port: 443" in ln for ln in lines)


def test_audit_ok_after_strip(tmp_path):
    (tmp_path / "usb-serial.yaml").write_text("Serial:\n  Device: /dev/ttyUSB0\n")
    assert mo.audit_overlays(tmp_path) == ('ok', [])


def test_audit_overrides_without_port(tmp_path):
    (tmp_path / "hat.yaml").write_text("Lora:\n  CS: 21\nTCP:\n  Port: 4403\n")
    status, lines = mo.audit_overlays(tmp_path)
    assert status == 'overrides' and "TCP" in lines[0]


def test_audit_unreadable_is_not_clean(tmp_path):
    (tmp_path / "hat.yaml").write_text("Lora: [unclosed\n")
    assert mo.audit_overlays(tmp_path)[0] == 'unreadable'


def test_no_raw_template_copy_into_config_d():
    wizard = (SRC / "launcher_tui/handlers/first_run.py").read_text()
    assert "shutil.copy2(src, dst)" not in wizard
    assert "shutil.copy2(source, dest)" not in wizard
    assert wizard.count("install_overlay(") >= 2
    cfm = (SRC / "config/config_file_manager.py").read_text()
    activate = cfm[cfm.index('"""Select a config from available.d'):]
    activate = activate[:activate.index("\n    def ")]
    assert "shutil.copy2" not in activate and "install_overlay(" in activate


def test_hardware_screen_renders_a_moved_port(capsys):
    # The render path only runs when there IS a finding — exercise it.
    from handlers.hardware import HardwareHandler
    h = HardwareHandler.__new__(HardwareHandler)
    h.ctx = MagicMock()
    finding = ('port_moved', ["usb-serial.yaml: Webserver: Port: 443 (API moves off :9443)"])
    with patch("utils.meshtasticd_overlay.audit_overlays", return_value=finding), \
         patch("handlers.hardware.subprocess.run", side_effect=FileNotFoundError), \
         patch("handlers.hardware.clear_screen"):
        h._detect_hardware()
    out = capsys.readouterr().out
    assert "moves the meshtasticd API off :9443" in out
    assert "Port: 443" in out


# ----------------------------------------------------------------------------
# MeshForge frontier review S1 (2026-09-28), ported: the installer's two raw
# `cp` sites now activate through scripts/sanitize_overlay.py (the ONE
# sanitizer), a failure installs nothing, and every shipped template must
# carry hardware keys only — the doctor must read `ok` on a raw copy.
# ----------------------------------------------------------------------------

_REPO = Path(__file__).resolve().parent.parent
_CLI = _REPO / "scripts" / "sanitize_overlay.py"
_BROKEN = """\
Lora:
  Module: sx1262
  CS: 21
  IRQ: 16
  Busy: 20
  Reset: 18

Webserver:
  Port: 443
  RootPath: /usr/share/meshtasticd/web

TCP:
  Port: 4403
"""


def test_shipped_templates_carry_only_hardware_keys():
    files = sorted((_REPO / "templates" / "available.d").glob("*.yaml"))
    # 29 since the 7 `Serial:`-only USB templates were deleted (B7,
    # 2026-09-30); a floor, so the glob cannot silently match nothing.
    assert len(files) >= 25, "the glob is aimed wrong"
    carrying = {f.name: sorted(set(yaml.safe_load(f.read_text()) or {})
                               & mo.HAT_OVERLAY_FORBIDDEN_KEYS) for f in files}
    assert {k: v for k, v in carrying.items() if v} == {}


def test_every_shipped_template_audits_ok_raw(tmp_path):
    config_d = tmp_path / "config.d"
    config_d.mkdir()
    for f in (_REPO / "templates" / "available.d").glob("*.yaml"):
        (config_d / f.name).write_text(f.read_text())
    status, lines = mo.audit_overlays(config_d)
    assert status == "ok", lines


def test_installer_has_no_raw_copy_into_config_d():
    text = (_REPO / "scripts" / "install_noc.sh").read_text()
    assert _cp_into_config_d(text) == [], _cp_into_config_d(text)
    # R3: the sibling script must not TEACH the raw cp either
    verify = (_REPO / "scripts" / "verify_post_install.sh").read_text()
    assert _cp_into_config_d(verify) == [], _cp_into_config_d(verify)
    # ONE activation path since B7 phase 2 (2026-09-30): the meshtasticd-radio
    # (HAT / CH341) branch. The USB-node branch activates NOTHING — meshtasticd
    # cannot drive a USB node (tests/test_installer_usb_and_module.py pins it).
    assert text.count("install_hat_overlay \"$AVAIL_DIR/") == 1
    assert "scripts/sanitize_overlay.py" in text
    assert "python3-yaml" in text


def _cli(*args):
    import subprocess
    return subprocess.run([sys.executable, str(_CLI), *map(str, args)],
                          capture_output=True, text=True, timeout=30)


def test_cli_strips_into_a_directory(tmp_path):
    src = tmp_path / "lora-MeshAdv-900M30S.yaml"
    src.write_text(_BROKEN)
    dst_dir = tmp_path / "config.d"
    r = _cli(src, f"{dst_dir}/")
    assert r.returncode == 0, r.stderr
    loaded = yaml.safe_load((dst_dir / src.name).read_text())
    assert "Webserver" not in loaded and "TCP" not in loaded and "Lora" in loaded
    assert "Webserver" in r.stdout and "config.yaml" in r.stdout


def test_cli_clean_template_keeps_bytes(tmp_path):
    src = _REPO / "templates" / "available.d" / "waveshare-sx1262.yaml"
    dst_dir = tmp_path / "config.d"
    r = _cli(src, f"{dst_dir}/")
    assert r.returncode == 0 and "clean" in r.stdout
    assert (dst_dir / src.name).read_text() == src.read_text()


def test_cli_unreadable_source_writes_nothing(tmp_path):
    dst_dir = tmp_path / "config.d"
    r = _cli(tmp_path / "missing.yaml", f"{dst_dir}/")
    assert r.returncode == 2 and "cannot read" in r.stderr
    assert not dst_dir.exists()


def _cp_into_config_d(text):
    """Every non-comment line that `cp`s ANYTHING into a config.d/ — a real
    copy or a hint that teaches one. Re-review R2 (2026-09-29): the old filter
    excluded lines whose prefix held `available.d`, i.e. the upstream-doc form
    `cp /etc/meshtasticd/available.d/x.yaml /etc/meshtasticd/config.d/` — the
    exact defect shape (#58) — and drilled red only because the old lines used
    `$AVAIL_DIR`."""
    return [ln.strip() for ln in text.splitlines()
            if not ln.lstrip().startswith("#")
            and re.search(r"\bcp\s", ln) and "config.d/" in ln]


def test_cp_guard_catches_the_upstream_doc_form_and_hints():
    upstream = "    cp /etc/meshtasticd/available.d/waveshare-sx1262.yaml /etc/meshtasticd/config.d/"
    hint = '    echo "Fix: sudo cp $CONFIG_DIR/available.d/<hat>.yaml $CONFIG_DIR/config.d/"'
    comment = "    # Activate ONE template into config.d/ — SANITIZED, never a raw cp (#58)."
    ok = "    python3 scripts/sanitize_overlay.py $src $dst_dir/  # into config.d/"
    assert len(_cp_into_config_d(upstream)) == 1
    assert len(_cp_into_config_d(hint)) == 1
    assert _cp_into_config_d(comment + "\n" + ok) == []
