"""meshtasticd config.d/ overlays: sanitize on activation, audit what is active.

2026-09-28: meshanchor-server's config.d/usb-serial.yaml (written by our own
setup wizard) carried `Webserver: Port: 443` for five months, and MeshAnchor
had no activation sanitizer and no surface that would show it. Port of
MeshForge's sanitizer + Config Doctor overlay check (#58).
"""
import os
import sys
from pathlib import Path
from unittest.mock import MagicMock, patch

sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', 'src', 'launcher_tui'))
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', 'src'))

import yaml

from utils import meshtasticd_overlay as mo

# The exact file meshanchor-server carried (before 2026-09-28).
OLD_USB_SERIAL = """\
# USB Serial Configuration
# Generated by MeshAnchor Setup Wizard

Serial:
  Device: /dev/ttyUSB0

TCP:
  Port: 4403

Webserver:
  Port: 443

Logging:
  LogLevel: info
"""

SRC = Path(__file__).parent.parent / "src"


def test_forbidden_keys_match_meshforge():
    # MeshForge core.meshtasticd_templates.HAT_OVERLAY_FORBIDDEN_KEYS.
    assert mo.HAT_OVERLAY_FORBIDDEN_KEYS == {
        'Webserver', 'TCP', 'Logging', 'MQTT', 'Bluetooth', 'General'}


def test_sanitize_strips_forbidden_keeps_the_rest():
    text, stripped = mo.sanitize_hat_overlay(OLD_USB_SERIAL)
    assert stripped == ['Logging', 'TCP', 'Webserver']
    assert yaml.safe_load(text) == {'Serial': {'Device': '/dev/ttyUSB0'}}


def test_sanitize_leaves_clean_and_malformed_alone():
    clean = "Lora:\n  Module: sx1262\n"
    assert mo.sanitize_hat_overlay(clean) == (clean, [])
    bad = "Lora: [unclosed\n"
    assert mo.sanitize_hat_overlay(bad) == (bad, [])


def test_install_overlay_writes_sanitized(tmp_path):
    src = tmp_path / "usb-serial.yaml"
    src.write_text(OLD_USB_SERIAL)
    dst = tmp_path / "out.yaml"
    assert "Webserver" in mo.install_overlay(src, dst)
    assert "Webserver" not in yaml.safe_load(dst.read_text())


def test_audit_absent(tmp_path):
    assert mo.audit_overlays(tmp_path / "nope") == ('absent', [])


def test_audit_flags_the_real_file(tmp_path):
    (tmp_path / "usb-serial.yaml").write_text(OLD_USB_SERIAL)
    status, lines = mo.audit_overlays(tmp_path)
    assert status == 'port_moved'
    assert any("Port: 443" in ln for ln in lines)


def test_audit_ok_after_strip(tmp_path):
    (tmp_path / "usb-serial.yaml").write_text("Serial:\n  Device: /dev/ttyUSB0\n")
    assert mo.audit_overlays(tmp_path) == ('ok', [])


def test_audit_overrides_without_port(tmp_path):
    (tmp_path / "hat.yaml").write_text("Lora:\n  CS: 21\nTCP:\n  Port: 4403\n")
    status, lines = mo.audit_overlays(tmp_path)
    assert status == 'overrides' and "TCP" in lines[0]


def test_audit_unreadable_is_not_clean(tmp_path):
    (tmp_path / "hat.yaml").write_text("Lora: [unclosed\n")
    assert mo.audit_overlays(tmp_path)[0] == 'unreadable'


def test_no_raw_template_copy_into_config_d():
    wizard = (SRC / "launcher_tui/handlers/first_run.py").read_text()
    assert "shutil.copy2(src, dst)" not in wizard
    assert "shutil.copy2(source, dest)" not in wizard
    assert wizard.count("install_overlay(") >= 2
    cfm = (SRC / "config/config_file_manager.py").read_text()
    activate = cfm[cfm.index('"""Select a config from available.d'):]
    activate = activate[:activate.index("\n    def ")]
    assert "shutil.copy2" not in activate and "install_overlay(" in activate


def test_hardware_screen_renders_a_moved_port(capsys):
    # The render path only runs when there IS a finding — exercise it.
    from handlers.hardware import HardwareHandler
    h = HardwareHandler.__new__(HardwareHandler)
    h.ctx = MagicMock()
    finding = ('port_moved', ["usb-serial.yaml: Webserver: Port: 443 (API moves off :9443)"])
    with patch("utils.meshtasticd_overlay.audit_overlays", return_value=finding), \
         patch("handlers.hardware.subprocess.run", side_effect=FileNotFoundError), \
         patch("handlers.hardware.clear_screen"):
        h._detect_hardware()
    out = capsys.readouterr().out
    assert "moves the meshtasticd API off :9443" in out
    assert "Port: 443" in out
