## Many device configs have been moved to /etc/meshtasticd/available.d
### To activate, simply copy or link the appropriate file into /etc/meshtasticd/config.d
---

Lora:
  Module: auto

Logging:
  LogLevel: info

Webserver:
  Port: 4403
  RootPath: /usr/share/meshtasticd/web

General:
  MaxNodes: 400
  MaxMessageQueue: 100
  ConfigDirectory: /etc/meshtasticd/config.d/
  AvailableDirectory: /etc/meshtasticd/available.d/
